{application, carre,
 [{description, "Tercio Test Web Server"},
  {vsn, "0.1.0"},
  {modules, [carre_sup,
             carre_app,
             carre_server,
             carre_socket,
             carre_client,
             carre,
             carre_handler,
             carre_post,
             carre_dyn_sup,
             carre_utils,
             carre_dispatcher]},
  {registered, [carre_sup, carre]},
  {applications, [kernel, stdlib, sasl]},
  {mod, {carre_app, []}}]}.
